In [1]:
import pandas as pd 
import dask.dataframe as da
import matplotlib.pyplot as plt 
import numpy as np 
import sys, os
sys.path.append('../src/')

In [2]:
df = pd.read_csv('../data/external/Heterogeneity of Human Neuroepithelial Cells and Early Radial Glia labels.tsv', sep='\t')

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/external/Heterogeneity of Human Neuroepithelial Cells and Early Radial Glia labels.tsv'

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df['Area_As_Annotated'].unique()

In [3]:
df['Area'].unique()

NameError: name 'df' is not defined

In [4]:
df2 = pd.read_csv('../data/external/whole_brain_bhaduri_labels.tsv', sep='\t')
df2

/var/folders/pd/jsjcl0fn7w57s5mfr34b20pm0000gn/T/ipykernel_29752/3935305708.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('../data/external/whole_brain_bhaduri_labels.tsv', sep='\t')


cell.name  age individual structure      area  \
0            GW14_CGE_AAACCTGGTAAAGGAG   14       GW14        GE       CGE   
1            GW14_CGE_AAACCTGGTTCCGTCT   14       GW14        GE       CGE   
2            GW14_CGE_AAACCTGTCGTCCAGG   14       GW14        GE       CGE   
3            GW14_CGE_AAACGGGCAGCCAGAA   14       GW14        GE       CGE   
4            GW14_CGE_AAACGGGGTGAACCTT   14       GW14        GE       CGE   
...                                ...  ...        ...       ...       ...   
691923  GW25_thalamus_TTTGTCACATGGTTGT   25       GW25  thalamus  thalamus   
691924  GW25_thalamus_TTTGTCAGTAGAAGGA   25       GW25  thalamus  thalamus   
691925  GW25_thalamus_TTTGTCAGTAGATTAG   25       GW25  thalamus  thalamus   
691926  GW25_thalamus_TTTGTCAGTTCGGCAC   25       GW25  thalamus  thalamus   
691927  GW25_thalamus_TTTGTCATCCTAGGGC   25       GW25  thalamus  thalamus   

       area.sub       clusterv2  clusterv2_id cell.type.v2  \
0           NaN          RG_4RG           191   radialglia   
1           NaN      Dividing_3            20     dividing   
2           NaN      Dividing_5            25     dividing   
3           NaN  Neuron_4Neuron           140       neuron   
4           NaN      Dividing_5            25     dividing   
...         ...             ...           ...          ...   
691923      NaN         Endo_11            32         endo   
691924      NaN     Astrocyte_4             4    astrocyte   
691925      NaN         Oligo_6           165        oligo   
691926      NaN     Astrocyte_4             4    astrocyte   
691927      NaN     Astrocyte_4             4    astrocyte   

        celltype.structure  ...                   matchname  \
0            radialglia_GE  ...                 GW14_RG_5RG   
1              dividing_GE  ...    GW14_Dividing_29Dividing   
2              dividing_GE  ...     GW14_Dividing_8Dividing   
3                neuron_GE  ...        GW14_Neuron_11Neuron   
4              dividing_GE  ...     GW14_Dividing_8Dividing   
...                    ...  ...                         ...   
691923       endo_thalamus  ...            GW25_Endo_24Endo   
691924  astrocyte_thalamus  ...  GW25_Astrocyte_17Astrocyte   
691925      oligo_thalamus  ...          GW25_Oligo_19Oligo   
691926  astrocyte_thalamus  ...  GW25_Astrocyte_17Astrocyte   
691927  astrocyte_thalamus  ...  GW25_Astrocyte_17Astrocyte   

                       clusterv1 ngene  numi   percent.mito percent.ribo  \
0                           RG_4   869  1481   1.290000e-13     0.232275   
1       GW14_Dividing_29Dividing   805  1845   1.220000e-37     0.270461   
2                    Dividing_37  1131  3101   5.790000e-19     0.341503   
3                       Neuron_4   776  1451   4.320000e-34     0.216402   
4                    Dividing_37  1097  2780   2.550000e-46     0.267986   
...                          ...   ...   ...            ...          ...   
691923                   Endo_45  2293  5242  5.000000e-153          NaN   
691924              Astrocyte_39  1846  3490  2.260000e-115          NaN   
691925                  Oligo_45  3094  6232  1.100000e-192          NaN   
691926              Astrocyte_39  1690  3270   1.360000e-94          NaN   
691927              Astrocyte_39  1728  3407  4.690000e-134          NaN   

          v1  ncount_rna  nfeature_rna                     cell.name.1  
0        5.0        1481           869       GW14_CGE_AAACCTGGTAAAGGAG  
1       29.0        1845           805       GW14_CGE_AAACCTGGTTCCGTCT  
2        8.0        3101          1131       GW14_CGE_AAACCTGTCGTCCAGG  
3       11.0        1451           776       GW14_CGE_AAACGGGCAGCCAGAA  
4        8.0        2780          1097       GW14_CGE_AAACGGGGTGAACCTT  
...      ...         ...           ...                             ...  
691923   NaN        5242          2293  GW25_thalamus_TTTGTCACATGGTTGT  
691924   NaN        3490          1846  GW25_thalamus_TTTGTCAGTAGAAGGA  
691925   NaN        

In [5]:
df2.shape

(691928, 25)

In [6]:
df2.columns

Index(['cell.name', 'age', 'individual', 'structure', 'area', 'area.sub',
       'clusterv2', 'clusterv2_id', 'cell.type.v2', 'celltype.structure',
       'lamina', 'cluster', 'celltype', 'cellabbreviation', 'clustercelltype',
       'matchname', 'clusterv1', 'ngene', 'numi', 'percent.mito',
       'percent.ribo', 'v1', 'ncount_rna', 'nfeature_rna', 'cell.name.1'],
      dtype='object')

In [7]:
for col in df2.columns:
    print(f'Unique values for col {col} are {df2[col].unique()}')

Unique values for col cell.name are ['GW14_CGE_AAACCTGGTAAAGGAG' 'GW14_CGE_AAACCTGGTTCCGTCT'
 'GW14_CGE_AAACCTGTCGTCCAGG' ... 'GW25_thalamus_TTTGTCAGTAGATTAG'
 'GW25_thalamus_TTTGTCAGTTCGGCAC' 'GW25_thalamus_TTTGTCATCCTAGGGC']
Unique values for col age are [14 17 18 19 20 22 25]
Unique values for col individual are ['GW14' 'GW17' 'GW18' 'GW18_2' 'GW19' 'GW20' 'GW20_31' 'GW20_34' 'GW22'
 'GW22T' 'GW25']
Unique values for col structure are ['GE' 'hypothalamus' 'neocortex' 'striatum' 'thalamus' 'allocortex'
 'claustrum' 'cerebellum' 'proneocortex' 'midbrain']
Unique values for col area are ['CGE' 'LGE' 'MGE' 'hypothalamus' 'motor' 'V1' 'somatosensory' 'striatum'
 'thalamus' 'parietal' 'PFC' 'hippocampus' 'temporal' 'claustrum'
 'preoptic' 'putamen' 'cerebellum' 'caudate' 'nucleusaccumbens'
 'cingulate' 'insula' 'midbrain']
Unique values for col area.sub are [nan 'ventral' 'caudal' 'dorsal' 'ventral_medial' 'left_hemisphere'
 '3rd_ventricle' 'anterior' 'pulminar']
Unique values for col clu

Unique values for col percent.ribo are [0.23227549 0.27046071 0.34150274 ... 0.10180891 0.12100554 0.17977073]
Unique values for col v1 are [ 5. 29.  8. 11. 12.  1. 24. 32. 14. 13. 26. 16.  3. 25.  7. 31. 19. 27.
 30. 20. 10. 21.  4.  6.  9. 22. 28. 33. 17. 23. 18. 15.  2. 35. 34. 36.
 39. 49. 38. 46. 44. 50. 43. 42. 48. 45. 40. 37. 47. 41. 51. 69. 63. 81.
 72. 53. 70. 60. 82. 65. 75. 62. 57. 74. 61. 64. 66. 56. 58. 78. 71. 80.
 52. 68. 77. 55. 73. 79. 59. 76. 54. 67. nan]
Unique values for col ncount_rna are [ 1481  1845  3101 ... 20777 24502 19481]
Unique values for col nfeature_rna are [ 869  805 1131 ... 5546 5953 5242]
Unique values for col cell.name.1 are ['GW14_CGE_AAACCTGGTAAAGGAG' 'GW14_CGE_AAACCTGGTTCCGTCT'
 'GW14_CGE_AAACCTGTCGTCCAGG' ... 'GW25_thalamus_TTTGTCAGTAGATTAG'
 'GW25_thalamus_TTTGTCAGTTCGGCAC' 'GW25_thalamus_TTTGTCATCCTAGGGC']


In [8]:
df2['age'].unique()


array([14, 17, 18, 19, 20, 22, 25])

## labels:

parietal cortex  
prefrontal cortex (PFC)  
motor = m1 = motor cortex  
v1 = visual cortex  
samtosensory cortex  
LGE (Lateral ganglionic emminence)  
CGE (caudal ganglionic emminence)  
temporal cortex  
MGE (medial ganglionic emminence) (progenitors that give rise to interneurons)  
insula  

## take out:
thalamus 
hypothalamus  
hippocampus 
claustrum  
cingulate           
caudate              
putamen              
preoptic             
cerebellum            
nucleusaccumbens  
striatum             
midbrain     

## Fixing the data

We will not use the Aldinger dataset , since it is from the Cerebellum, which will have different forms of neurons than the cerebral cortex. Also, we can't use the Eze et. al since clusters are not labeled. Instead, we'll use the following

1. `df1`: Bhaduri et. al, 2020, https://www.nature.com/articles/s41586-020-1962-0 (our primary dataset)
2. `df2`: Bhaduri et. al, 2021, https://www.nature.com/articles/s41586-021-03910-8 
3. `df3`: Allen brain atlas, m1 region: https://cells.ucsc.edu/?bp=brain&ds=allen-celltypes+human-cortex
4. `df4`: Allen brain atlas, cortex region: https://cells.ucsc.edu/?bp=brain&ds=allen-celltypes+human-cortex
5. `df5`: Delgado: https://cells.ucsc.edu/?ds=human-cortical-lineage
6. Chinese paper

In [10]:
df1 = pd.read_csv('../data/external/primary_bhaduri_labels.tsv', sep='\t')
df2 = pd.read_csv('../data/external/whole_brain_bhaduri_labels.tsv', sep='\t')
df3 = pd.read_csv('../data/external/allen_m1_region_labels.tsv', sep='\t')
df4 = pd.read_csv('../data/external/allen_cortex_labels.tsv', sep='\t')

/var/folders/pd/jsjcl0fn7w57s5mfr34b20pm0000gn/T/ipykernel_29752/3559954611.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('../data/external/whole_brain_bhaduri_labels.tsv', sep='\t')


In [11]:
df2.columns

Index(['cell.name', 'age', 'individual', 'structure', 'area', 'area.sub',
       'clusterv2', 'clusterv2_id', 'cell.type.v2', 'celltype.structure',
       'lamina', 'cluster', 'celltype', 'cellabbreviation', 'clustercelltype',
       'matchname', 'clusterv1', 'ngene', 'numi', 'percent.mito',
       'percent.ribo', 'v1', 'ncount_rna', 'nfeature_rna', 'cell.name.1'],
      dtype='object')

In [12]:
df2['matchname']

0                        GW14_RG_5RG
1           GW14_Dividing_29Dividing
2            GW14_Dividing_8Dividing
3               GW14_Neuron_11Neuron
4            GW14_Dividing_8Dividing
                     ...            
691923              GW25_Endo_24Endo
691924    GW25_Astrocyte_17Astrocyte
691925            GW25_Oligo_19Oligo
691926    GW25_Astrocyte_17Astrocyte
691927    GW25_Astrocyte_17Astrocyte
Name: matchname, Length: 691928, dtype: object

We'll rename some values of `df2` to make them consistent with `df1`.

In [13]:
df2['celltype'] = df2['celltype'].replace({'RG' : 'Radial Glia', 'CR': 'Cajal Retzius'})
df2['celltype'].value_counts()

Excitatory Neuron    257489
Interneuron          156146
Dividing              69797
Radial Glia           64608
Outlier               32377
Neuron                28586
Astrocyte             24908
Oligodendrocyte       19827
IPC                   15230
Microglia             13697
Endothelial            8899
Vascular                240
Cajal Retzius           124
Name: celltype, dtype: int64

Now that `df1` and `df2` are properly aligned, let's map the values from `df3` and `df4` into the values from `df1` and `df2`.

Gluta = excititory
gaba = inhib

L2/3 IT: excit, between hemispheres  
Pvalb: inhib   
sst: inhib  
vip: inhin  
lamp5: inhib  
L6 ct: excit cortical-thalamic  
oligo: oligodendricites  
L6b: excit  
L6 it: excit  
L5/6 NP: excit   
Sncg: inhib   
L5 et: excit   
astro: astrocyte  
L6 IT car3: excit   
OPC: OPC  
MicroPVM: microglia (double check)  
sst chodl: inhib  
endo: Endothelial  
VLMC: Look up  

In [14]:
df3_mapping = {
    'L2/3 IT': 'Excitatory Neuron',
    'L5 IT': 'Interneuron', 
    'Pvalb': 'Interneuron',
    'Sst': 'Interneuron',
    'Vip': 'Interneuron',
    'Lamp5': 'Interneuron',
    'L6 CT': 'Interneuron', 
    'Oligo': 'Oligodendrocyte', 
    'L6b': 'Excitatory Neuron',
    'L6 IT': 'Excitatory Neuron',
    'L5/6 NP': 'Excitatory Neuron',
    'Sncg': 'Interneuron', 
    'L5 ET': 'Excitatory Neuron', 
    'Astro': 'Astrocyte',
    'L6 IT Car3': 'Excitatory Neuron', 
    'OPC': 'OPC',
    'Micro-PVM': 'Microglia',
    'Sst Chodl': 'Interneuron',
    'Endo': 'Endothelial',
    'VLMC': 'Vascular',
}

In [15]:
df3['subclass_label'] = df3['subclass_label'].replace(df3_mapping)

In [16]:
df4_mapping = {
    'IT': 'Interneuron',
    'L4 IT': 'Interneuron',
    'VIP': 'Interneuron',
    'PVALB': 'Interneuron',
    'L6 CT': 'Interneuron', 
    'LAMP5': 'Interneuron',
    'SST': 'Interneuron',
    'Exclude': 'Exclude',
    'Oligodendrocyte': 'Oligodendrocyte',
    'Astrocyte': 'Astrocyte',
    'L6b': 'Excitatory Neuron',
    'L5/6 IT Car3': 'Excitatory Neuron',
    'L5/6 NP': 'Excitatory Neuron',
    'OPC': 'OPC',
    'Microglia': 'Microglia',
    'PAX6' : 'Progenitors', # DROP THESE, progenitors should not be in postnatal 
    'L5 ET': 'Excitatory Neuron',
    'Endothelial' : 'Endothelial',
    'Pericyte': 'Pericyte',
    'VLMC': 'Vascular'
}

IT: excit (inter hemispheric)  
L4 IT: layer 4 excit  
VIP: interneuron (inhib)
pvalb:  
L6 CT:  corticalthalamic (excit)  
LAMP5:  
SST  :
L5/6 NP:  excit 
PAX6:  drop 

In [17]:
df4['subclass_label'] = df4['subclass_label'].replace(df4_mapping)

Now, let's grab the columns we're interested in into new DataFrames, and write these out to our `data/processed`.

In [18]:
df1_reduced = df1[['Type']]
df1_reduced = df1_reduced[df1_reduced['Type'] != 'Outlier']

df2_reduced = df2[['celltype']].rename(columns={'celltype': 'Type'})
df2_reduced = df2_reduced[df2_reduced['Type'] != 'Outlier']

df3_reduced = df3[['subclass_label']].rename(columns={'subclass_label': 'Type'})
df3_reduced = df3_reduced[df3_reduced['Type'] != 'Outlier']

df4_reduced = df4[['subclass_label']].rename(columns={'subclass_label': 'Type'})
df4_reduced = df4_reduced[df4_reduced['Type'] != 'Exclude']

In [111]:
from sklearn.preprocessing import LabelEncoder

def encode(data):
    le = LabelEncoder()
    data.loc[:, 'Type'] = le.fit_transform(data.loc[:, 'Type'])
    
    return data
    
for df in df1_reduced, df2_reduced, df3_reduced, df4_reduced:
    print(df['Type'].value_counts())
    print('\n')

Excitatory Neuron     122958
Radial Glia            29563
Inhibitory Neuron      20609
Microglia               4510
IPC                     3863
Red blood cells         2451
OPC                     1888
Mural                    363
Endothelial              271
Name: Type, dtype: int64


Excitatory Neuron    257489
Interneuron          156146
Dividing              69797
Radial Glia           64608
Neuron                28586
Astrocyte             24908
Oligodendrocyte       19827
IPC                   15230
Microglia             13697
Endothelial            8899
Vascular                240
Cajal Retzius           124
Name: Type, dtype: int64


Interneuron          41560
Excitatory Neuron    30968
Oligodendrocyte       2942
Astrocyte              568
OPC                    283
Microglia              108
Endothelial             64
Vascular                40
Name: Type, dtype: int64


Interneuron          39313
Excitatory Neuron     3114
Oligodendrocyte       1932
Astrocyte             118

In [112]:
display(df1_reduced.head())
display(df2_reduced.head())

Type
0         Radial Glia
1         Radial Glia
2  Excitatory Neuron 
3  Excitatory Neuron 
4  Excitatory Neuron

Type
0        Radial Glia
1           Dividing
2           Dividing
3  Excitatory Neuron
4           Dividing

Let's write these iterim results out before continuing to encode our targets

In [114]:
df1_reduced.to_csv('../data/interim/bhaduri_2020_labels.csv')
df2_reduced.to_csv('../data/interim/bhaduri_2021_labels.csv')
df3_reduced.to_csv('../data/interim/allen_m1_labels.csv')
df4_reduced.to_csv('../data/interim/allen_cortex_labels.csv')

## Mapping label sets to similar categorical variables

In order to train our model, we need to encode the categorical target variables consistently across all label files. To do this, we'll first take the union of all unique target values in df1$,...,$df4, then map these to integers and apply to our categorical columns.

In [115]:
datasets = [df1_reduced, df2_reduced, df3_reduced, df4_reduced]
unique_targets = list(set(np.concatenate([df['Type'].unique() for df in datasets])))
unique_targets, len(unique_targets)

(['IPC',
  'Microglia',
  'Cajal Retzius',
  'Red blood cells',
  'Excitatory Neuron',
  'Neuron',
  'Mural',
  'Endothelial',
  'Astrocyte',
  'Oligodendrocyte',
  'Interneuron',
  'Progenitors',
  'Excitatory Neuron ',
  'OPC',
  'Radial Glia',
  'Pericyte',
  'Dividing',
  'Vascular',
  'Inhibitory Neuron'],
 19)

Now we define an encoder on our unique targets

In [116]:
le = LabelEncoder()
le = le.fit(unique_targets)

In [117]:
le.transform(unique_targets)

array([ 6,  9,  1, 17,  4, 11, 10,  3,  0, 13,  8, 15,  5, 12, 16, 14,  2,
       18,  7])

In [120]:
df1_reduced['Type'] = le.transform(df1_reduced['Type'])
df2_reduced['Type'] = le.transform(df2_reduced['Type'])
df3_reduced['Type'] = le.transform(df3_reduced['Type'])
df4_reduced['Type'] = le.transform(df4_reduced['Type'])

In [128]:
df1_reduced.index.name = 'cell'
df1_reduced

Type
cell        
0         16
1         16
2          5
3          5
4          5
...      ...
189404    10
189405    10
189406     5
189407     9
189408     5

[186476 rows x 1 columns]

In [130]:
df1_reduced.to_csv('test.csv')

df = pd.read_csv('test.csv', index_col='cell')
df

Type
cell        
0         16
1         16
2          5
3          5
4          5
...      ...
189404    10
189405    10
189406     5
189407     9
189408     5

[186476 rows x 1 columns]

## Cleaning the gene expression matrices

Now that we've fixed the label files, let's make sure the gene expression matrices are formatted as we expect.

We should have a cell $\times$ gene expression for each label DataFrame, and the columns kept should be the intersection of all columns

In [26]:
import dask.dataframe as dd
import sys 
sys.path.append('../src')
from models.lib.data import *

In [27]:
allen_cortex = GeneExpressionData(
    '../data/interim/allen_cortex_T.csv',
    '../data/interim/allen_cortex_labels.csv',
    'Type',
    skip=3,
)

bhaduri_primary = GeneExpressionData(
    '../data/processed/primary.csv',
    '../data/processed/meta_primary_labels.csv',
    'Type'
)

In [28]:
bhaduri_primary[0]

(tensor([0., 0., 0.,  ..., 0., 0., 0.]), 8)

In [29]:
allen_cortex[1]

(tensor([0., 0., 0.,  ..., 0., 0., 0.]), 'Interneuron')

In [30]:
allen_cortex[0]

(tensor([0., 0., 0.,  ..., 0., 0., 5.]), 'Interneuron')

In [31]:
len(allen_cortex[1][0])

50281

In [32]:
allen_cortex.get_features()

[]

In [33]:
m1T.columns

NameError: name 'm1T' is not defined

In [ ]:
df.columns

In [ ]:
m1cols = [x.split('|')[0] for x in m1T.columns]
cortcols = list(df.columns)

In [ ]:
len(set(m1cols).intersection(set(cortcols)))

In [ ]:
len(cortcols)

In [ ]:
prim = pd.read_csv('../data/processed/primary.csv', nrows=1)
prim

In [ ]:
primcols = list(prim.columns)

len(set(cortcols).intersection(primcols))

In [ ]:
set(cortcols) - set(primcols)

In [ ]:
test1 = pd.DataFrame(np.ones([10, 10]))
test2 = pd.DataFrame(np.zeros([10,10]), columns=range(10, 0, -1))

pd.concat([test1, test2])

In [ ]:
list(range(10, 0, -1))