In [29]:
import numpy as np 
import torch
import anndata as an

from typing import List

In [32]:
data = an.read_h5ad('../data/pancreas/pancreas.h5ad', backed='r+')

/Users/julian/miniconda3/envs/base-data-science/lib/python3.9/site-packages/anndata/compat/__init__.py:180: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
  warn(
/Users/julian/miniconda3/envs/base-data-science/lib/python3.9/site-packages/anndata/compat/__init__.py:180: FutureWarning: Moving element from .uns['neighbors']['connectivities'] to .obsp['connectivities'].

This is where adjacency matrices should go now.
  warn(


In [38]:
currgenes = data.var.index
refgenes = currgenes[1:]

In [39]:
clean_sample(
    data.X,
    refgenes,
    currgenes
)

array([[ 1.2636875 , -0.27988526, -0.08080115, ..., -0.17193557,
         2.4617705 , -0.22981071],
       [-0.41321668, -0.27988526, -0.08080115, ..., -0.17193557,
        -0.14446081, -0.22981071],
       [-0.41321668, -0.27988526,  5.5823755 , ..., -0.17193557,
        -0.14446081, -0.22981071],
       ...,
       [ 2.9582937 , -0.23932047, -0.0678516 , ..., -0.16555843,
        -0.13694999, -0.22630794],
       [-0.19474961,  0.43301603, -0.07221387, ..., -0.16770668,
        -0.13948013, -0.2274879 ],
       [-0.4107381 , -0.24773662, -0.06931861, ..., -0.16628088,
        -0.13780086, -0.22670473]], dtype=float32)

In [3]:
def clean_sample(
    sample: torch.Tensor,
    refgenes: List[str],
    currgenes: List[str],
) -> torch.Tensor:

    intersection = np.intersect1d(currgenes, refgenes, return_indices=True)
    indices = intersection[1] # List of indices in sorted(currgenes) that equal sorted(refgenes)
    
    axis = (1 if sample.ndim == 2 else 0)
    sample = np.take(sample, indices, axis=axis)
    
    return sample


In [26]:
currgenes = ['a', 'c', 'd', 'b', 'e']
refgenes =  ['d', 'e', 'a', 'f']

data = np.array(
            [[4,   3,   2,   1,   0],
             [0,   1,   2,   3,   4]]
)

In [27]:
clean_sample(data, refgenes, currgenes)

array([[4, 2, 0],
       [0, 2, 4]])

In [18]:
intersection = np.intersect1d(currgenes, refgenes, return_indices=True)
indices = intersection[1] # List of indices in sorted(currgenes) that equal sorted(refgenes)

In [19]:
indices

array([0, 2])