In [89]:
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd 
import plotly.express as px 
import plotly.graph_objects as go 
import seaborn as sns
import os 
import sys
sys.path.append('../src')
from helper import DATA_FILES_AND_NAMES_DICT

In [90]:
files, names = DATA_FILES_AND_NAMES_DICT.keys(), DATA_FILES_AND_NAMES_DICT.values()
files = [f'{x[:-4: ]}_labels.csv' for x in files]

In [91]:
files

['primary_bhaduri_labels.csv',
 'allen_cortex_labels.csv',
 'allen_m1_region_labels.csv',
 'whole_brain_bhaduri_labels.csv']

Next, let's make a folder for our paper images

In [92]:
os.makedirs('./paper_plots/', exist_ok=True)

Let's make sure there is no whitespace in our labels

In [93]:
vals = []
dfs = []
for file in files:
    df = pd.read_csv(f'../data/interim/labels/{file}', index_col='Unnamed: 0')
    vals.extend(df['Type'].value_counts().index)
    dfs.append(df)

In [94]:
set(vals)

{'Astrocyte',
 'Cajal Retzius',
 'Dividing',
 'Endothelial',
 'Excitatory Neuron',
 'Exclude',
 'IPC',
 'Interneuron',
 'Microglia',
 'Mural',
 'Neuron',
 'OPC',
 'Oligodendrocyte',
 'Outlier',
 'Pericyte',
 'Progenitors',
 'Radial Glia',
 'Red blood cells',
 'Vascular'}

Now, we can start looking at the distribution of labels across all datasets

In [95]:
dfs = dict(zip(names, dfs))

In [134]:
for file, df in dfs.items():
    vals = df['Type'].value_counts()

    fig = go.Figure(
        data=[go.Bar(x=vals.index, y=vals.values)],
        layout=go.Layout(
            title=f'Distribution of Class Labels, for {file} Dataset', 
            xaxis_title='Label', 
            yaxis_title='Frequency'
        )
    )
    fig.show()

In [118]:
subtype1 = pd.read_csv('../data/raw/whole_brain_bhaduri_labels.tsv', sep='\t')
subtype2 = pd.read_csv('../data/raw/primary_bhaduri_labels.tsv', sep='\t')

/var/folders/pd/jsjcl0fn7w57s5mfr34b20pm0000gn/T/ipykernel_40852/2946144356.py:1: DtypeWarning:

Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.



In [116]:
subtype1.columns

Index(['cell.name', 'age', 'individual', 'structure', 'area', 'area.sub',
       'clusterv2', 'clusterv2_id', 'cell.type.v2', 'celltype.structure',
       'lamina', 'cluster', 'celltype', 'cellabbreviation', 'clustercelltype',
       'matchname', 'clusterv1', 'ngene', 'numi', 'percent.mito',
       'percent.ribo', 'v1', 'ncount_rna', 'nfeature_rna', 'cell.name.1'],
      dtype='object')

In [117]:
from models.lib.data import *

In [ ]:
datasets = {}

for file, name in zip(files, names):
    datasets = {
        
    }

In [120]:
test = GeneExpressionData(
    f'../data/processed/data/primary.csv', 
    f'../data/processed/labels/primary_bhaduri_labels.csv',
    'Type'
)

In [121]:
test[0]

(tensor([0., 0., 0.,  ..., 0., 0., 0.]), 16)

In [123]:
%%time
test[1]

CPU times: user 5.99 ms, sys: 576 µs, total: 6.56 ms
Wall time: 6.19 ms


(tensor([0., 0., 0.,  ..., 0., 0., 0.]), 16)

In [124]:
len(test[1][0])

16319

In [126]:
from torch.utils.data import DataLoader

In [127]:
test = DataLoader(test, batch_size=4, num_workers=0)

In [129]:
%%time 
next(iter(test))

CPU times: user 25.6 ms, sys: 20.8 ms, total: 46.4 ms
Wall time: 76.9 ms


[tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 1.2663,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([16, 16,  4,  4])]